# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePermission',
            fields=[
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=30)),
                ('view_param_pk', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=140, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
